name: Python-CI
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'python/**/*'
      - '**/*.py'
      - '**/*.toml'
      - .github/workflows/python-ci.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]
        poetry-version: [1.6.1]
        project: ["datashaper", "examples"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: ${{ matrix.project }} - Install dependencies
        shell: bash
        working-directory: ./python/${{ matrix.project }}
        run: poetry install

      - name: ${{ matrix.project }} - Check Formatting
        working-directory: ./python/${{ matrix.project }}
        run: |
          poetry run poe check_format

      - name: ${{ matrix.project }} - Check
        working-directory: ./python/${{ matrix.project }}
        run: |
          poetry run poe check

      - name: ${{ matrix.project }} - Test
        working-directory: ./python/${{ matrix.project }}
        run: |
          poetry run poe test
